name: corona
description: a realtime reliable source to have CoronaVirus Stats and news all over the worl

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  # cupertino_icons: ^0.1.2
  http: ^0.12.0+4
  flutter_icons: ^1.0.0+1
  provider: ^4.0.4
  easy_localization: ^2.0.2
  flutter_sim_country_code: ^0.0.3
  superellipse_shape: ^0.1.5
  shared_preferences: ^0.5.6+3
  # firebase_core: ^0.4.4+3
  # firebase_admob: ^0.9.3+1
  # ads: ^1.0.0
  flutter_native_admob: ^2.1.0
  connectivity: ^0.4.8+2


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
   - assets/langs/
   - assets/images/
 
  fonts:
    - family: Almarai
      fonts:
        - asset: assets/fonts/Almarai-Regular.ttf
        - asset: assets/fonts/Almarai-Bold.ttf
          weight: 700
        - asset: assets/fonts/Almarai-Light.ttf
          weight: 300
        - asset: assets/fonts/Almarai-ExtraBold.ttf
          weight: 800
