name: corona
description: a realtime reliable source to have CoronaVirus Stats and news all over the world
 
version: 1.1.0+1.1

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  connectivity: ^3.0.6
  http: ^0.13.3
  countries_utils: ^1.0.0
  provider: ^6.0.0
  easy_localization: ^3.0.0
  flutter_sim_country_code: ^0.1.1
  superellipse_shape: ^ 0.2.0-nullsafety.0
  shared_preferences: ^2.0.7


 
dev_dependencies: 
  flutter_lints: ^1.0.4

flutter:

  uses-material-design: true
  assets:
   - assets/translations/
   - assets/images/
 
  fonts:
    - family: Almarai
      fonts:
        - asset: assets/fonts/Almarai-Regular.ttf
        - asset: assets/fonts/Almarai-Bold.ttf
          weight: 700
        - asset: assets/fonts/Almarai-Light.ttf
          weight: 300
        - asset: assets/fonts/Almarai-ExtraBold.ttf
          weight: 800
